name: Publish Jest Report

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' 

      - name: Install dependencies
        run: npm install 

      - name: Run Sanity Tests And Generate Report
        run: npm run test:sanity

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: test-results/report

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4