name: Run Tests by Group
on:
  workflow_dispatch:
    inputs:
      testGroup:
        description: 'Select a test group to filter tests'
        required: true
        default: 'all'
        type: choice
        options:         
          - all
          - sanity
          - single_character
          - all_characters
          - multiple_characters
          - filter_characters

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Install dependencies
        run: npm install 

      - name: Run tests with group
        run: |
          if [ "${{ github.event.inputs.testGroup }}" == "all" ]; then
            npm run test:all
          elif [ "${{ github.event.inputs.testGroup }}" == "sanity" ]; then
            npm run test:sanity
          elif [ "${{ github.event.inputs.testGroup }}" == "single_character" ]; then
            npm run test:single_character
          elif [ "${{ github.event.inputs.testGroup }}" == "all_characters" ]; then
            npm run test:all_characters
          elif [ "${{ github.event.inputs.testGroup }}" == "multiple_characters" ]; then
            npm run test:multiple_characters
          elif [ "${{ github.event.inputs.testGroup }}" == "filter_characters" ]; then
            npm run test:filter_characters
          fi
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-report.html